worker:
  persistence:
    enabled: true
    storageClass: "standard"  # Change this based on your cluster's storage class
    accessModes:
      - ReadWriteOnce
    size: 3Gi

master:
  persistence:
    enabled: true
    storageClass: "standard"
    accessModes:
      - ReadWriteOnce
    size: 1Gi
